config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root to: 'tweet_sanas#index'
  resources :tweet_sanas do
    resources :comment_sanas, only: :create
    collection do
      get 'search'
    end
  end
  resources :user_sanas, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment_sana.rb
class CommentSana < ApplicationRecord
  belongs_to :tweet_sana
  belongs_to :user
end

app/models/tweet_sana.rb
class TweetSana < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comment_sanas

  def self.search(search)
    if search != ""
      TweetSana.where('text LIKE(?)', "%#{search}%")
    else
      TweetSana.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweet_sanas
  has_many :comment_sanas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_sanas_controller.rb
class CommentSanasController < ApplicationController
  def create
    comment = CommentSana.create(comment_params)
    redirect_to "/tweet_sanas/#{comment.tweet_sana.id}"
  end

  private
  def comment_params
    params.require(:comment_sana).permit(:text).merge(user_id: current_user.id, tweet_sana_id: params[:tweet_sana_id])
  end
end

app/controllers/tweet_sanas_controller.rb
class TweetSanasController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @tweets = TweetSana.includes(:user).order("created_at DESC")
  end

  def new
    @tweet_sana = TweetSana.new
  end

  def create
    TweetSana.create(tweet_params)
  end  

  def destroy
    tweet = TweetSana.find(params[:id])
    tweet.destroy
  end

  def edit
  end

  def update
    tweet = TweetSana.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    @comment = CommentSana.new
    @comments = @tweet_sana.comment_sanas.includes(:user)
  end

  def search
    @tweets = TweetSana.search(params[:keyword])
  end

  private
  def tweet_params
    params.require(:tweet_sana).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet_sana = TweetSana.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/user_sanas_controller.rb
class UserSanasController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweet_sanas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_sanas_helper.rb
module CommentSanasHelper
end

app/helpers/tweet_sanas_helper.rb
module TweetSanasHelper
end

app/helpers/user_sanas_helper.rb
module UserSanasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicTweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>
         <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
            <%= link_to "投稿する", new_tweet_sana_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright PicTweet 2019.
      </p>
    </footer>
  </body>
</html>

app/views/tweet_sanas/_form_sana.html.erb
 <%= form_with(model: tweet_sana, local: true) do |form| %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>

app/views/tweet_sanas/_tweet_sana.html.erb
 <div class="content_post" style="background-image: url(<%= tweet.image %>);">
       <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
           <li>
            <%= link_to '詳細', tweet_sana_path(tweet.id), method: :get %>
          </li>
         <% if user_signed_in? && current_user.id == tweet.user_id %>
           <li>
            <%= link_to '編集', edit_tweet_sana_path(tweet.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', tweet_sana_path(tweet.id), method: :delete %>
          </li>
         <% end %>
        </ul>
      </div>
      <p><%= tweet.text %></p>
      <span class="name">
        <a href="/user_sanas/<%= tweet.user.id %>">
          <span>投稿者</span><%= tweet.user.nickname %>
        </a>
      </span>
    </div>

app/views/tweet_sanas/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweet_sanas/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweet_sanas/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form_sana", locals: { tweet_sana: @tweet_sana } %>
  </div>
</div>

app/views/tweet_sanas/index.html.erb
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet_sana", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweet_sanas/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= render partial: "form_sana", locals: { tweet_sana: @tweet_sana } %>
  </div>
</div>

app/views/tweet_sanas/search.html.erb
<%= form_with(url: search_tweet_sanas_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet_sana", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweet_sanas/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet_sana.image %>);">
   <% if user_signed_in? && current_user.id == @tweet_sana.user_id %>
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_tweet_sana_path(@tweet_sana.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', tweet_sana_path(@tweet_sana.id), method: :delete %>
        </li>
      </ul>
    </div>
  <% end %>
    <p><%= @tweet_sana.text %></p>
    <span class="name">
      <a href="/users/<%= @tweet_sana.user.id %>">
        <span>投稿者</span><%= @tweet_sana.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@tweet_sana, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
     <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/user_sanas/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweet_sanas/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/user_sanas/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet_sanas/tweet_sana", locals: { tweet: tweet }%>
  <% end %>
</div>